### ISSUE TITLE
[Android Bootcamp] Project 3 - Review my app

### ISSUE THREAD

**Issue by marcferna** [marcferna/android-twitter-client#2]
Here is the app. I apologize, didn't have enough time to complete the optional parts.
/cc @nesquena @thecodepath

**Comment by codepathreview** [comment]
Decent job overall Marc!  A few notes after checking out the code:
- Consider polishing your UI for better readability to make it look like the actual Twitter app
- Good job formatting the relative time stamp (Consider externalizing the logic into Util class)
- Consider using the [ProgressBar](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) indicating network requests
- Consider using Parcelable or Serializable ([benefits](http://stackoverflow.com/a/5551155)) for model objects
- Consider adding null checks in JSON parsing for robust error handling
- Consider implementing more optional/bonus features.
- Consider adding ActiveAndroid to the `Tweet` and `User`. See the [persistence guide](https://github.com/thecodepath/android_guides/wiki/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](https://github.com/thecodepath/android_guides/wiki/ActiveAndroid-Guide) for more details.

Here's a detailed [Project 3 Feedback Guide here](https://gist.github.com/nesquena/a41220c54c9550f69599) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
